import 'package:trace_craft/features/image_search/domain/models/search_image.dart';

/// Curated high-resolution reference images across categories
/// ready out-of-the-box for instant offline tracing and demo browsing.
class CuratedSketches {
  static final List<SearchImage> items = [
    // Portraits
    SearchImage(
      id: 'curated_portrait_1',
      title: 'Minimalist Side Profile Portrait',
      previewUrl: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Amina Filkins',
      photographerUrl: 'https://www.pexels.com/@amina-filkins/',
      width: 1080,
      height: 1350,
      category: 'Portraits',
      provider: ImageSourceProvider.pexels,
      tags: ['portrait', 'face', 'expressive', 'eyes'],
    ),
    SearchImage(
      id: 'curated_portrait_2',
      title: 'Dramatic High-Contrast Silhouette',
      previewUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 1440,
      category: 'Portraits',
      provider: ImageSourceProvider.pexels,
      tags: ['man', 'lighting', 'contrast', 'proportions'],
    ),
    // Animals
    SearchImage(
      id: 'curated_animal_1',
      title: 'Majestic Roaring Lion',
      previewUrl: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Wildlife',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1200,
      height: 800,
      category: 'Animals & Wildlife',
      provider: ImageSourceProvider.pexels,
      tags: ['lion', 'wildlife', 'mane', 'animal'],
    ),
    SearchImage(
      id: 'curated_animal_2',
      title: 'Golden Retriever Puppy Face',
      previewUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Chewy',
      photographerUrl: 'https://www.pexels.com/@chewy/',
      width: 1080,
      height: 1080,
      category: 'Animals & Wildlife',
      provider: ImageSourceProvider.pexels,
      tags: ['dog', 'puppy', 'cute', 'pet'],
    ),
    SearchImage(
      id: 'curated_animal_3',
      title: 'Soaring Eagle in Motion',
      previewUrl: 'https://images.pexels.com/photos/145939/pexels-photo-145939.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/145939/pexels-photo-145939.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Birds',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 720,
      category: 'Animals & Wildlife',
      provider: ImageSourceProvider.pexels,
      tags: ['bird', 'eagle', 'wings', 'feathers'],
    ),
    // Anime & Cartoons / Line Art
    SearchImage(
      id: 'curated_anime_1',
      title: 'Chibi Mascot Character',
      previewUrl: 'https://images.pexels.com/photos/163036/mario-luigi-figures-funny-163036.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/163036/mario-luigi-figures-funny-163036.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Games',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 800,
      category: 'Anime & Cartoons',
      provider: ImageSourceProvider.pexels,
      tags: ['cartoon', 'character', 'fun', 'easy'],
    ),
    // Flowers & Botanical
    SearchImage(
      id: 'curated_flower_1',
      title: 'Blooming Red Rose Petals',
      previewUrl: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Flora',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 1080,
      category: 'Flowers & Botanical',
      provider: ImageSourceProvider.pexels,
      tags: ['rose', 'flower', 'botanical', 'petals'],
    ),
    SearchImage(
      id: 'curated_flower_2',
      title: 'Sunflower Head Close-up',
      previewUrl: 'https://images.pexels.com/photos/46216/sunflower-flowers-bright-yellow-46216.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/46216/sunflower-flowers-bright-yellow-46216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Nature',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 1080,
      category: 'Flowers & Botanical',
      provider: ImageSourceProvider.pexels,
      tags: ['sunflower', 'yellow', 'symmetry'],
    ),
    // Architecture & Vehicles
    SearchImage(
      id: 'curated_arch_1',
      title: 'Eiffel Tower Perspective',
      previewUrl: 'https://images.pexels.com/photos/532826/pexels-photo-532826.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/532826/pexels-photo-532826.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Thorsten technoman',
      photographerUrl: 'https://www.pexels.com/@technoman/',
      width: 1080,
      height: 1600,
      category: 'Architecture',
      provider: ImageSourceProvider.pexels,
      tags: ['paris', 'tower', 'architecture', 'lines'],
    ),
    SearchImage(
      id: 'curated_vehicle_1',
      title: 'Vintage Classic Sports Car',
      previewUrl: 'https://images.pexels.com/photos/248687/pexels-photo-248687.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/248687/pexels-photo-248687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Auto',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1200,
      height: 800,
      category: 'Vehicles & Cars',
      provider: ImageSourceProvider.pexels,
      tags: ['car', 'vintage', 'automobile', 'proportions'],
    ),
    // Easy for Beginners
    SearchImage(
      id: 'curated_easy_1',
      title: 'Single Ceramic Coffee Cup',
      previewUrl: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Still Life',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 1080,
      category: 'Easy for Beginners',
      provider: ImageSourceProvider.pexels,
      tags: ['cup', 'coffee', 'basic shapes', 'beginner'],
    ),
    SearchImage(
      id: 'curated_easy_2',
      title: 'Fresh Apple with Leaf',
      previewUrl: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
      originalUrl: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      photographer: 'Pixabay Fruit',
      photographerUrl: 'https://www.pexels.com/@pixabay/',
      width: 1080,
      height: 1080,
      category: 'Easy for Beginners',
      provider: ImageSourceProvider.pexels,
      tags: ['apple', 'fruit', 'shading', 'beginner'],
    ),
  ];
}
